version: 0.2

phases:
  pre_build:
    commands:
      - docker login -u adikhare31 -p PurvaManu_0302
      - echo "Logged in to Docker Hub"

  build:
    commands:
      - echo "Build Started"
      - docker build -t mindtrack-nginx .
      - docker run -d -p 3000:80 mindtrack-nginx

  post_build:
    commands:
      - docker tag mindtrack-nginx:latest adikhare31/mindtrack-project
      - docker push adikhare31/mindtrack-project
      - echo "Image pushed to the docker hub repo"

artifacts:
  files:
    - '**/*'
