version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b0v5y0o9
      - echo "Logged in to Docker Hub"

  build:
    commands:
      - echo "Build Started"
      - docker build -t mindtrack-nginx .

  post_build:
    commands:
      - docker tag mindtrack-nginx:latest public.ecr.aws/b0v5y0o9/mindtrack-repo:latest
      - docker push public.ecr.aws/b0v5y0o9/mindtrack-repo:latest
      - echo "Image pushed to the docker hub repo"

artifacts:
  files:
    - '**/*'
