version: 0.2

phases:
  pre_build:
    commands:
      - docker login -u adikhare31 -p PurvaManu_0302
      - echo "Logged in to Docker Hub"

  build:
    commands:
      - echo "Build Started"
      - docker build -t mindtrack-nginx .
      - docker run -d -p 3000:80 mindtrack-nginx

  post_build:
    commands:
      - docker tag mindtrack-nginx 299332719675.dkr.ecr.us-east-1.amazonaws.com/mindtrack-repo:latest
      - docker push 299332719675.dkr.ecr.us-east-1.amazonaws.com/mindtrack-repo
      - echo "Image pushed to the docker hub repo"

artifacts:
  files:
    - '**/*'
