apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindtrack-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
      - name: mindtrack-container
        image: public.ecr.aws/b0v5y0o9/mindtrack-repo:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
